package raidenGame;

import java.awt.Graphics;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Bullet.java
//  @ Date : 9/3/2007
//  @ Author : 
//
//




public class Bullet extends GameBaseElement {

        public Bullet(){
            super();
        }
        
        public void draw(Graphics g){
            g.fillRect(getPositionX(),getPositionY(),2,2);
        }
        
        public void move(){
            setPositionY(getPositionY()-getSpeed());
        }
}
