package raidenGame;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Enemy.java
//  @ Date : 9/3/2007
//  @ Author : 
//
//




public class Enemy extends GameBaseElement {

        public Bullet bullets[];

        public Enemy(){
            super();
            prepareBullets();
        }

        public Enemy(int hitPoint, int speed, int positionX, int positionY){
            super(hitPoint, speed, positionX, positionY);
            prepareBullets();
        }

        public void prepareBullets(){
            bullets = new Bullet[10];
            for (int i = 0; i < bullets.length; i++) {
                bullets[i] = new Bullet();
            }
        }
}
