package raidenGame;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GameBaseElement.java
//  @ Date : 9/3/2007
//  @ Author : 
//
//




public abstract class GameBaseElement {
	private int hitPoints;
	private int speed;
	private int positionX;
	private int positionY;
        private boolean alive;

        public GameBaseElement(){
            this(1,5,0,0);
            setAlive(true);
        }

        public GameBaseElement(int hitPoint, int speed, int positionX, int positionY){
            this.setHitPoints(hitPoint);
            this.setSpeed(speed);
            this.setPositionX(positionX);
            this.setPositionY(positionY);
            setAlive(true);
        }

    public int getHitPoints() {
        return hitPoints;
    }

    public void setHitPoints(int hitPoints) {
        this.hitPoints = hitPoints;
    }

    public int getSpeed() {
        return speed;
    }

    public void setSpeed(int speed) {
        this.speed = speed;
    }

    public int getPositionX() {
        return positionX;
    }

    public void setPositionX(int positionX) {
        this.positionX = positionX;
    }

    public int getPositionY() {
        return positionY;
    }

    public void setPositionY(int positionY) {
        this.positionY = positionY;
    }

    public boolean isAlive() {
        return alive;
    }

    public void setAlive(boolean alive) {
        this.alive = alive;
    }

        
}
