package raidenGame;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : HighScorePanel.java
//  @ Date : 9/3/2007
//  @ Author : 
//
//




public class HighScorePanel {
}
