package raidenGame;

//

import java.awt.Graphics;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Player.java
//  @ Date : 9/3/2007
//  @ Author : 
//
//
public class Player extends GameBaseElement {

    public Bullet bullets[];

    public int bulletDelay;
    
    public enum DIRECTION {
        UP, DOWN, LEFT, RIGHT
        }

    public Player() {
        super();
        prepareBullets();
    }

    public Player(int hitPoint, int speed, int positionX, int positionY) {
        super(hitPoint, speed, positionX, positionY);
        prepareBullets();
    }

    public void prepareBullets() {
        bullets = new Bullet[10];
//            for (int i = 0; i < bullets.length; i++) {
//                bullets[i] = new Bullet();
//            }
    }

    public void draw(Graphics g) {
        g.fillRect(getPositionX(), getPositionY(), 5, 5);
    }

    public void drawBullets(Graphics g) {
        for (int i = 0; i < bullets.length; i++) {
            Bullet bullet = bullets[i];
            if(bullet != null)
                bullet.draw(g);
        }

    }

    public void move(Player.DIRECTION direction) {
        
        if(direction.equals(DIRECTION.UP)){
            setPositionY(getPositionY() - getSpeed());
        }
        if(direction.equals(DIRECTION.DOWN)){
            setPositionY(getPositionY() + getSpeed());
        }
        if(direction.equals(DIRECTION.LEFT)){
            setPositionX(getPositionX() - getSpeed());
        }
        if(direction.equals(DIRECTION.RIGHT)){
            setPositionX(getPositionX() + getSpeed());
        }
        
        //System.out.println("Player Current Position X: "+getPositionX()+" Y: "+getPositionY());
    }
    
    public void moveBullets(){
        for (int i = 0; i < bullets.length; i++) {
            Bullet bullet = bullets[i];
            if(bullet != null)
                bullet.move();
        }
    }
    
    public void fire(){
        for (int i = 0; i < bullets.length; i++) {
                if(bullets[i] == null && bulletDelay <= 0){
                    bullets[i] = new Bullet();
                    bullets[i].setPositionX(this.getPositionX());
                    bullets[i].setPositionY(this.getPositionY());
                    System.out.println("bullet # "+(i+1)+" is lunched");
                    bulletDelay = 20;
                }
        }
    }
    
    public void update(){
        if(bulletDelay > 0){
            bulletDelay -= 1;
            //System.out.println("bulletDelay = "+bulletDelay);
        }
        
        for (int i = 0; i < bullets.length; i++) {
            if(bullets[i] != null && bullets[i].getPositionY() < 0){
                bullets[i] = null;
            }
        }
    }
}
