package raidenGame;

import java.awt.Container;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RaidenGame.java
//  @ Date : 9/3/2007
//  @ Author : 
//
//




public class RaidenGame extends JFrame implements WindowListener{

private static int DEFAULT_FPS = 80;

  private RaidenPanel rp;        // where the game elements is drawn

  public RaidenGame(int period)
  { super("The Worm Chase");
    makeGUI(period);

    addWindowListener( this );
    pack();
    setResizable(false);
    setVisible(true);
  }  // end of WormChase() constructor


  private void makeGUI(int period)
  {
    Container c = getContentPane();    // default BorderLayout used

    rp = new RaidenPanel(this, period);
    c.add(rp, "Center");

    JPanel ctrls = new JPanel();   // a row of textfields
    ctrls.setLayout( new BoxLayout(ctrls, BoxLayout.X_AXIS));

  }  // end of makeGUI()


  // ----------------- window listener methods -------------

    @Override
  public void windowActivated(WindowEvent e) 
  { rp.resumeGame();  }

    @Override
  public void windowDeactivated(WindowEvent e) 
  {  rp.pauseGame();  }


    @Override
  public void windowDeiconified(WindowEvent e) 
  {  rp.resumeGame();  }

    @Override
  public void windowIconified(WindowEvent e) 
  {  rp.pauseGame(); }


    @Override
  public void windowClosing(WindowEvent e)
  {  rp.stopGame();  }

    @Override
  public void windowClosed(WindowEvent e) {}
    @Override
  public void windowOpened(WindowEvent e) {}

  // ----------------------------------------------------

  public static void main(String args[])
  { 
    int fps = DEFAULT_FPS;
    if (args.length != 0)
      fps = Integer.parseInt(args[0]);

    int period = (int) 1000.0/fps;
    System.out.println("fps: " + fps + "; period: " + period + " ms");

    new RaidenGame(period);    // ms
  }

}
